import { ISidebarButton } from './ISidebarButton';

export class FileGuideButton implements ISidebarButton {
    // tslint:disable-next-line:max-line-length
    icon = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4QUIEw0mZVsjgQAAAiNJREFUSMet1UuoTWEYBuDnuHXqJOUSJbkdMqBcimgN1lbCYBkYSJKJONIaiMiAoZEYLTnuTBQysUaS9o5FBsdQESdCUuRSrh1sk/9ot8M+e/FOVutf//re/3u/73v/Dg2I48oZrMMXQ8MwjMa2Wq168ncbOpoI6liN/uZvf8BYnMZ0HKrVqvuaN4xoev+O/lqt+nAox4/jyni8CVlfi+OKZpJhrbJqgQ6MxDeswK44rmxvRdAOvuETzqEXj3HkbxK1i3dYG+LU0Y2iFEGWF/NwFh+xMU2ip7VatY63DTUZG4hKSbQzBOtCz1B/GjGEk0/ARcT4EAq7MMuLOdiQJtHXVoPyt+CL8AivMArncSD0/0Q8yfJiaimCLC+6cAr70yRalybRAPbiMBbjGa7jVJYXnWUkWoXXONawNh0nsCDUYwpuYS762pVoLe7gR8hoB+7ifnhuDZPfhzVlajAZm7E0y4vR2BQCj8MArmB9OMikMgQvcDxNohuhLd/iJVbiSKjJBVwK623X4DJ6srwYg4NBjtuYnSbRoBmOwhJsKZPB1SDH0TDBy4OVP2/Ysxvvca/tDNIk+pDlRQ+qgezmoKFledEb5JmPZWkSfS41aGkS9WFWKOLH4Pt7guafMS1Nov5/soo0iV4iyvKiGzNC2z5Ik+jZf/GiBqJHwTbawu8kqv/D/VBvlcFwzIzjSrtX52Dwmc0xmwnOhv7/UjKDzhDjF34CWgai1qHbevcAAAAASUVORK5CYII=';
    label = 'FILE_GUIDE';
}